### ISSUE TITLE
Command to output parseable list of scripts arguments?

### ISSUE THREAD

**Issue by jansorg** [Trepan-Debuggers/bashdb#42]
In BashSupport Pro, I'm showing the current arguments for a frame (e.g. `$1 = first, $2 = second`).
I'm using `info args` for this.

But for the entry point of the session, this doesn't work because `show args` is supposed to show the arguments passed to the script.
- Unfortunately, the output of `show args` is not fit for parsing, e.g. because of white-space handling.
- I don't know how to detect if a frame is the top-level/entry-level frame of the session. I'm launching with `bashdb ...`, which inserts at least two frames

What would be the best way to show the script arguments `$1`, `$2`, etc. instead of `info args` to the user when the current frame  is the top-level frame?
I'm fine to add my own info arg command, but wanted to ask here first.

**Comment by rocky** [comment]
The approach I have been using in other debuggers (and programs like the open-source Mathematica) is to write a command-line independent library routine. With this in place, the command-line or other kinds of front-ends call that and processes it further for its needs.

Following this pattern, [lines 74-93 of command/info_sub/args](https://github.com/Trepan-Debuggers/bashdb/blob/bash-5.2/command/info_sub/args.sh#L74-L92) would be extracted and put inside a function in, say, `lib/frame_args.sh`. The `_Dbg_msg()` and `_Dbg_printf` in that code would be changed though. Instead of the print functions, the function might just set the values into an array like _Dbg_frame_args`. 

Something like this was done for the sorting routine. However, in the sorting routine, I should have made the return argument less generic.

How does this sound? What are your thoughts?

**Comment by jansorg** [comment]
I'm sorry, I didn't fully understand your comment. I think my initial post is not clear.
What I'd like is a command to show function arguments when in a function call and script arguments to the debugged script when at top-level. That way I could show values for $1, $2, etc. as a regular `echo $1`, `echo $2` would do in a regular script.
I noticed `_Dbg_stack_size` which should allow me to implement this.

We probably shouldn't change the output of `show args`, as it's using output similar to GDB (I don't know GDB much).

**Comment by jansorg** [comment]
In my fork, I added a command `info args_bsp`, which I'm testing now. This probably only works for invocations like `bashdb script.sh arg1 arg2`, though.
https://github.com/Trepan-Debuggers/bashdb/pull/45/files#diff-e795abfea2f8e9709ece2837e7981c6c8ea133c0603cc8ebe79b30b9344996f8R68-R76

**Comment by jansorg** [comment]
This is similar to https://github.com/Trepan-Debuggers/bashdb/issues/41, and I'm closing this because I'll need to implement this differently.
