### ISSUE TITLE
Breakpoints in files sourced with a relative path are not hit

### ISSUE THREAD

**Issue by jansorg** [Trepan-Debuggers/bashdb#50]
For BashSupport Pro, I received this bug report: https://github.com/BashSupport-Pro/bashsupport-pro/issues/189
If you don't mind, I'd be glad for your input.

I've debugged this in bashdb.
I think that it's two different bugs, but I'm not sure how to fix them.

## Bug 1

1. bashdb is launched from the directory which contains `main.bash` and `lib.bash`
2. When breakpoint in `lib.bash` is hit, `info stack` displays `./lib.bash` even though the current working directory has been changed by the script to "$HOME"

Would it be possible to show absolute file paths in `info stack`? That would resolve the ambiguity how to resolve relative paths. 

## Bug 2

1. bashdb is launched from a directory, which is not the parent of `main.bash` and `lib.bash`
2. Running the bashdb commands below, the script just ends without hitting the breakpoint in `lib.bash`

I think it's not hit because none of the candidates to resolve a relative path (`./lib.bash`) is the right one. AFAIK it's searching in the initial working dir and current working dir of the script.

I think it may be possible to fix this if the paths to `source` could be recorded as absolute paths.
But I'm not sure if that's even possible.

## Test Case
File `main.bash`:

```bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

. ./lib.bash # if this is changed into ". $DIR/lib.bash", then the breakpoint is hit
cd "$HOME"
libFunction world
```

File `lib.bash`:
```bash
libFunction() {
    echo hello "$1" # <--- breakpoint on this line
}
```

bashdb session:
```text
# ./bashdb -L . /path/to/main.bash
load /path/to/lib.bash
break /path/to/lib.bash:1
cont
info stack
```

**Comment by rocky** [comment]
> For BashSupport Pro, I received this bug report: [BashSupport-Pro/bashsupport-pro#189](https://github.com/BashSupport-Pro/bashsupport-pro/issues/189) If you don't mind, I'd be glad for your input.
> 
> I've debugged this in bashdb. I think that it's two different bugs, but I'm not sure how to fix them.
> 
> ## Bug 1
> 1. bashdb is launched from the directory which contains `main.bash` and `lib.bash`
> 2. When breakpoint in `lib.bash` is hit, `info stack` displays `./lib.bash` even though the current working directory has been changed by the script to "$HOME"
> 
> Would it be possible to show absolute file paths in `info stack`? That would resolve the ambiguity how to resolve relative paths.
> 

Definitely we should store resolved paths and show that in `info stack`. I am surprised that wasn't done, and I believe this is what I do in other debuggers.

> ## Bug 2
> 1. bashdb is launched from a directory, which is not the parent of `main.bash` and `lib.bash`
> 2. Running the bashdb commands below, the script just ends without hitting the breakpoint in `lib.bash`
> 
> I think it's not hit because none of the candidates to resolve a relative path (`./lib.bash`) is the right one. AFAIK it's searching in the initial working dir and current working dir of the script.
> 
> I think it may be possible to fix this if the paths to `source` could be recorded as absolute paths. But I'm not sure if that's even possible.

Give me a day to think about this one and try your test case below. Thanks.


> 
> ## Test Case
> File `main.bash`:
> 
> ```shell
> DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
> cd "$DIR"
> 
> . ./lib.bash # if this is changed into ". $DIR/lib.bash", then the breakpoint is hit
> cd "$HOME"
> libFunction world
> ```
> 
> File `lib.bash`:
> 
> ```shell
> libFunction() {
>     echo hello "$1" # <--- breakpoint on this line
> }
> ```
> 
> bashdb session:
> 
> ```
> # ./bashdb -L . /path/to/main.bash
> load /path/to/lib.bash
> break /path/to/lib.bash:1
> cont
> info stack
> ```

**Comment by rocky** [comment]
(BTW bashdb option `--basename`  was created precisely because long names are intended internally, but in testing we need the basename values)

**Comment by rocky** [comment]
@jansorg I just tried to reproduce the bugs and I am not seeing this from the command line. Basically bashdb _is_ resolving all file paths so there is no ambiguity. In a debugger command if I issue `break ./lib.bash:1`, then either it is found because the path hasn't been changed or it is not and you are prompted to issue a `load` command for it.

So right now I am missing some essential step(s) to reproduce this.  Here is what I tried: 

![image](https://github.com/user-attachments/assets/7d835c97-98cc-4df5-bd0c-b86479aec6fa)

and: 

![image](https://github.com/user-attachments/assets/f4930a41-e018-4bba-836a-7b375a8540c1)

Note that paths are filled out in the breakpoint structure even though I specify a short name. 

Is basename somehow getting set in the environment you are running?

**Comment by jansorg** [comment]
@rocky Thanks for testing!

For the first case, I probably didn't make it clear that `info stack` is printing the relative path.
In the screenshot, it's printing `--> 0 in file './lib.bash' at line 1`. There's no clear indication which path it's relative to. An absolute path would allow to resolve this. `./lib.bash` seems to be the path passed to the `source` command.
Screenshot first case:

![image](https://github.com/user-attachments/assets/d62e24c2-8fe9-4eea-9f34-29dfca43eaba)

For the second case, a breakpoint is not hit if `bashdb` is not launched from the directory containing `main.bash`. 
In the example, bashdb is in `..` and I'm debugging `sources/main.bash`.

Screenshot 2nd case:

![image](https://github.com/user-attachments/assets/afcf2090-f18c-4029-bb03-2fc886b99b88)

**Comment by rocky** [comment]
Thanks for the easy-to-follow and narrowed problem. 

There is promise for various improvements to the code which will narrow this kind of problem. I have two PR's that I hope to provide concrete examples the ideas. Let me describe them in broader terms here. 

First of all the unresolved names come from bash. This is the way it is storing paths in its backtrace. Best would be to get it to store this information in absolute path name form. Then many things would be simpler.

However, it has always been the case that the code has mechanisms for ameliorating this kind of thing. There is an associative array called `_Dbg_filename2canonic`  that is used to map a path name reported by bash into a path accessible to the user.  In the process of tracing the program, the relative path is valid at some point in time. So if bashdb can resolve the relative path to an absolute one, it can record this information in `_Dbg_filename2canonic` so that when the relative path is no longer valid, it has recorded what worked in the past. 

In the debugger,  you can get this mapping that has been stored by using the bashdb/gdb command `info files`. 

The first PR adds to the debugger callback hook an update to the mapping for the file name that bash gives as the file of the the current frame with what it can resolve in the filename.  

No doubt,  I have made various mistakes here. That's why I work on debuggers. 

The second PR is about doing the same kind of thing when you issue the "load" and "breakpoint" commands. Both of these will fail if the file is not found, so this is some sort of minimal plausibility check. 

I should also mention one other mechanism that gdb provides and bashdb uses under the covers; there is a variable called `_Dbg_dir` which is a environment-like "PATH" variable which gives a list of directories to search when encountering a relative file.  In gdb, it can be changed using the "dir" command. I don't have this implemented in bashdb, but it could easily be added.

**Comment by jansorg** [comment]
Closing this as the issues I reported are now fixed.
